# Generated by Django 4.1 on 2022-08-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='timedate_created',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='blog_post',
            old_name='timedate_modiefied',
            new_name='datetime_modified',
        ),
    ]
